global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8080', 'user-service-sidecar:20000']

  - job_name: 'post-service'
    static_configs:
      - targets: ['post-service:8080', 'post-service-sidecar:20000']

  - job_name: 'connections-service'
    static_configs:
      - targets: ['connections-service:8080', 'connections-service-sidecar:20000']
